server:
  port: 30000

spring:
  application:
    name: gulimall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
alibaba:
  cloud:
    access-key: LTAI5tRS1i76DTb7jHE3ndZt
    secret-key: mq2xV60JXJZ96xYNClTxzo3fdKvP3h
    oss:
      endpoint: oss-cn-hangzhou.aliyuncs.com
      bucket: gulimall-denghui